version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    ports:
      - "3001:3001"
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
